name: bot

on:
  issue_comment:
    types:
      - created

jobs:
  approve:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/approve' &&
      github.actor == 'int128'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.issue.owner,
              repo: context.issue.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
            })

  merge:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/merge' &&
      github.actor == 'int128'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const runLink = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            try {
              const { data: pull } = await github.rest.pulls.get({
                owner: context.issue.owner,
                repo: context.issue.repo,
                pull_number: context.issue.number,
              })
              core.info(`Updating ${pull.base.ref} to ${pull.head.ref}@${pull.head.sha}`)
              await github.rest.git.updateRef({
                owner: context.issue.owner,
                repo: context.issue.repo,
                ref: `heads/${pull.base.ref}`,
                sha: pull.head.sha,
              })
            } catch (error) {
              core.error(error)
              return await github.rest.issues.createComment({
                owner: context.issue.owner,
                repo: context.issue.repo,
                issue_number: context.issue.number,
                body: `## :x: Unable to merge\n@${context.actor} ${String(error)}\n${runLink}`,
              })
            }
            return await github.rest.issues.createComment({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: context.issue.number,
              body: `Updated ${pull.base.ref} to ${pull.head.sha} by fast-forward on behalf of @${context.actor}`
            })
